### PR TITLE
Modulesync update

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
https://github.com/Katello/puppet-pulp/pull/162 will fix the failure

**Comment by ehelms** [comment]
@stbenjam PR job is passing

**Comment by ekohl** [comment]
ACK though it looks like that both travis jobs need to pass since you pushed to this remote instead of a fork.

**Comment by ehelms** [comment]
@ekohl admin privileges FTW :)

**Comment by ekohl** [comment]
That's cheating ;)

**Pull request merged**
