### PR TITLE
fixes #12000 - add support for remote execution ssh plugin

### PR DESCRIPTION
**Pull request by stbenjam**
This is fugly, I don't even know if its worth including and perhaps waiting until foreman-proxy is at the top level.

### CODE REVIEW

**Comment by ehelms** [comment]
Only ugly due to formatting change, I'd be OK with this if it means people playing with it in nightlies. I'll let @bbuckingham comment as well since he is handling the change you mention.

**Comment by stbenjam** [comment]
Yea the formatting is nasty, but I meant wrapping the plugin in the capsule module itself isn't very nice either

**Comment by bbuckingham** [comment]
I am Ok with the ugliness to make the functionality available.  I am sure it will mean some merge conflicts when the scenario-based changes go in, but that is to be expected.

**Comment by ehelms** [comment]
ACK

**Pull request merged**
