### PR TITLE
Fixes #9157: Allow customizing the crane port.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Requires https://github.com/Katello/puppet-crane/pull/2

**Comment by jlsherrill** [comment]
This port # seems to be hardcoded into katello:

**Comment by jlsherrill** [comment]
We'd also need to somehow know the port on a per-capsule basis which is more complicated....

We could allow them to change it but it must be uniform across their capsules.  Or we could contact the capsules and fetch the port prior to deployment

**Comment by jlsherrill** [comment]
Given all that it may not be worth doing?

**Comment by ehelms** [comment]
You have me convinced.. until someone produces a viable use case for this I am all for not supporting it until then.

**Pull request closed without merging**
