### PR TITLE
Fixes #14359 - SSL errors on capsule sync

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
These changes worked downstream, currently testing them upstream

**Comment by ehelms** [comment]
Whats a downstream? ;)

**Comment by johnpmitsch** [comment]
@ehelms err... I tested this "elsewhere" ;)

**Comment by ehelms** [comment]
Are you done with your testing? I am satisfied with the change.

**Comment by johnpmitsch** [comment]
not yet, testing now!

John Mitsch
Red Hat Engineering
(860)-967-7285
irc: jomitsch

**Comment by johnpmitsch** [comment]
@ehelms install is working fine with these changes :+1:

**Comment by ehelms** [comment]
ACk - thanks @johnpmitsch !

**Pull request merged**
