### PR TITLE
fixes #11338 - use asymmetric routing for pulp/pulp.task queues

### PR DESCRIPTION
**Pull request by stbenjam**
Do not merge yet, we need new packages first.

### CODE REVIEW

**Comment by ehelms** [comment]
ACK

**Comment by ehelms** [comment]
What new packages do we need for this?

**Comment by stbenjam** [comment]
The newest qpid dispatch router, @jlsherrill always managed to get them into Koji, not sure how to do that..

**Comment by stbenjam** [comment]
Since we moved to using qpid from epel, we have the packages that have this feature. This is ready to go.

**Comment by ehelms** [comment]
ACK

**Pull request merged**
